// This file is generated by scripts/generate-i18n-config.ts
// Do not edit this file manually.
module.exports = {
  "defaultLocale": "en",
  "locales": [
    "en",
    "sl"
  ],
  "pages": {
    "*": [
      "common",
      "form"
    ],
    "/": [
      "form"
    ]
  }
};
