import './globals.css';

import useTranslation from 'next-translate/useTranslation';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  // TODO: localize
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { lang } = useTranslation();
  return (
    <html lang={lang}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
