import { writeFileSync } from 'fs';
import { join } from 'path';

import { defaultLocale, locales, pages } from '../locales/index';

// Create i18n.js with given locales
const i18n = {
  defaultLocale,
  locales,
  pages,
};

const fileContent = `// This file is generated by scripts/generate-i18n-config.ts
// Do not edit this file manually.
module.exports = ${JSON.stringify(i18n, null, 2)};
`;

console.log('Writing i18n.js...');

// Write i18n.js
writeFileSync(join(__dirname, '..', 'i18n.js'), fileContent, {
  encoding: 'utf-8',
});

console.log('Done. 🎉');
