name: i18n
on:
  push:
  pull_request:

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - name: Check Localization
        run: |
          pnpm i18n
