name: Lint
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - uses: zerodays/action-infisical@v1
        with:
          infisical_token: ${{ secrets.INFISICAL_TOKEN }}
          environment: "staging"
      - name: Lint
        run: |
          source .env && pnpm tsc
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - name: Typecheck
        run: |
          pnpm tsc
