name: 'Test'
on:
  pull_request:
  workflow_dispatch:
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
